"""'InitialMigration'

Revision ID: 278a22621c36
Revises: 
Create Date: 2022-05-29 21:14:07.654215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278a22621c36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###
